JCC = javac
JFLAG = -g
AI = AIAI.java Course.java Planner.java Section.java Major.java \
	 Planner.java PlannerUnit.java Student.java 

UI = LeftPanel.java MainFrame.java Options.java RightPanel.java #App.java
	 
TEST = AIUnitTests.java  
OTHER = CsSectionsTextfileUpdater.java
#DATA = open_seats.txt spring_2017_cs_sections.txt cs_sections.txt \
		OutputForSectionUnitTest.txt

docs: 
	javadoc -linksource AIAI.java Course.java Planner.java \
								Section.java Major.java Planner.java \
								PlannerUnit.java Student.java
